common: &common
  adapter: postgresql
  encoding: utf8

development:
  <<: *common
  database: grokphoto

test:
  <<: *common
  database: grokphoto-test

production:
  <<: *common
  database: grokphoto-production