common: &common
  adapter: postgresql
  encoding: utf8
  username: dev
  password: dev
  host: localhost

development:
  <<: *common
  database: grokphoto

test:
  <<: *common
  database: grokphoto-test

production:
  <<: *common
  database: grokphoto-production
