#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: grok-photo
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-2450369-23"

#staging:
#  app: grokphoto-staging
#  config: &default
#    BUNDLE_WITHOUT: "development:test"

#demo:
#  app: grokphoto-demo
#  config: *default